apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: memory-test
  name: memory-test
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: memory-test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: memory-test
    spec:
      containers:
      - image: isaackuang/jvm-memory-test
        imagePullPolicy: Always
        name: memory-test
        env:
          - name: ALLOC_HEAP_MB
            value: "1"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /dump
          name: dump-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: dump-volume
        emptyDir: {}